### ISSUE TITLE
unable to identify the type System.Linq.Enumerable+WhereSelectArrayIterator

### ISSUE THREAD

**Issue by kaisbejaoui** [autofac/autofac-analysis#1]
Hello,

First of all thank you for the amazing work you're doing on autofac and autofac.Analysis!
I have a component registered with something like the following code (which works fine)

``` c#
var list = new List<double> {1.0, 2.0, 3.5};
var containerBuilder = new ContainerBuilder();
containerBuilder.RegisterInstance(list.Where(x => x != 1.0)).As<IEnumerable<double>>();
```

When using Autofac.Analysis the above type is not handeled correctly and an exception is thrown when parsing the type. In fact, the following code fails

``` c#
var list = new List<double> {1.0, 2.0, 3.5};
var type = list.Where(x => x!= 1.0).GetType().AssemblyQualifiedName;
_parsed = TypeIdentifier.Parse(type);
```

The issue is probably a Sprache issue and not a Autofac.Analysis one.

kind regards,

Kaïs Bejaoui

**Comment by nblumhardt** [comment]
Thanks for the note. I think the problem may be sidestepped by using types rather than strings internally, now that the analysis engine runs in-process rather than across a network as it once did. Will investigate (and sorry about the long delay :-))

**Comment by nblumhardt** [comment]
#3, if it's merged, will address this.
